# Generated by Django 5.0.3 on 2024-03-14 14:33

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('gender', models.CharField(default=' ', max_length=100)),
                ('mastercategory_image', models.ImageField(blank=True, null=True, upload_to=api.models.master_category_image)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('name', 'gender')},
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default=None, max_length=255)),
                ('description', models.TextField(default=None)),
                ('gender', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to=api.models.master_service_image)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mastercategory')),
            ],
            options={
                'unique_together': {('service_name', 'gender')},
            },
        ),
    ]
