# Generated by Django 5.0.3 on 2024-03-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterservice',
            unique_together=set(),
        ),
    ]
