# Generated by Django 5.0.3 on 2024-03-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_masterservice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterservice',
            unique_together={('service_name', 'gender')},
        ),
    ]
